version: "3"

services:
    dvwa:
        build: ./image_php-apache
        ports:
            - "8080:80"
        volumes:
            - ./dvwa:/var/www/html/
        links:
            - db
        depends_on:
            -db
    db:
        image: mysql
        container_name: db
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MARIADB_ROOT_PASSWORD: p@ssw0rd
            MYSQL_DATABASE: dvwa
            MYSQL_USER: dvwa
            MYSQL_ROOT_PASSWORD: p@ssw0rd
            MYSQL_PASSWORD: p@ssw0rd
        volumes:
            - dvwa_db:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        environment:
            MYSQL_USER: dvwa
            MYSQL_ROOT_PASSWORD: p@ssw0rd
            MYSQL_PASSWORD: p@ssw0rd
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: p@ssw0rd
volumes:
    dvwa_db:
networks:
    default:
